[2025-04-13T22:52:07.645+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T22:52:07.656+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T22:52:07.663+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T22:52:07.665+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T22:52:07.677+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_table_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T22:52:07.682+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T22:52:07.683+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-04-13T22:52:07.684+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_external_table_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp1r_k4fjk']
[2025-04-13T22:52:07.684+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask create_external_table_task
[2025-04-13T22:52:07.717+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host f545404fc07f
[2025-04-13T22:52:07.759+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T22:52:07.760+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T22:52:07.760+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T22:52:07.761+0000] {logging_mixin.py:190} INFO - Current task name:create_external_table_task state:running start_date:2025-04-13 22:52:07.657075+00:00
[2025-04-13T22:52:07.761+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T22:52:07.761+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T22:52:07.762+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-13T22:52:07.762+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-13T22:52:07.762+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-13T22:52:07.790+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': "\n          CREATE OR REPLACE EXTERNAL TABLE `nyc-projects-455321.building_permits.external_table`\n          OPTIONS (\n            format = 'PARQUET',\n            uris = ['gs://nyc-projects-455321-bucket/raw/building_permits.parquet']\n          )\n        ", 'useLegacySql': False}}'
[2025-04-13T22:52:07.791+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3af71f1632af090c5287ffa426aef981
[2025-04-13T22:52:09.051+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3af71f1632af090c5287ffa426aef981 is completed. Checking the job status
[2025-04-13T22:52:09.095+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T22:52:09.096+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=create_external_table_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T225207, end_date=20250413T225209
[2025-04-13T22:52:09.120+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-13T22:52:09.121+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-13T22:52:09.121+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-13 22:51:56.480715+00:00
[2025-04-13T22:52:09.122+0000] {logging_mixin.py:190} INFO - Task hostname:f545404fc07f operator:BigQueryInsertJobOperator
[2025-04-13T22:52:09.136+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T22:52:09.144+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T22:52:09.145+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T23:07:48.460+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:07:48.472+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:07:48.477+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:07:48.477+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T23:07:48.483+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_table_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T23:07:48.487+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:07:48.488+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-04-13T23:07:48.490+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_external_table_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp3rf5hnjg']
[2025-04-13T23:07:48.491+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask create_external_table_task
[2025-04-13T23:07:48.515+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 3aaac60a2eb2
[2025-04-13T23:07:48.554+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T23:07:48.555+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T23:07:48.555+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T23:07:48.556+0000] {logging_mixin.py:190} INFO - Current task name:create_external_table_task state:running start_date:2025-04-13 23:07:48.472372+00:00
[2025-04-13T23:07:48.556+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T23:07:48.556+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:07:48.557+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-13T23:07:48.557+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-13T23:07:48.558+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-13T23:07:48.586+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          CREATE OR REPLACE EXTERNAL TABLE `nyc-projects-455321.building_permits.external_table`\n          OPTIONS (\n            format = \'PARQUET\',\n            uris = [\'{ ti.xcom_pull(task_ids="local_to_gcs_task") }\']\n          )\n        ', 'useLegacySql': False}}'
[2025-04-13T23:07:48.587+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_40710c060f1f134ba504552b7f2a3b3b
[2025-04-13T23:07:49.618+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }; reason: invalid, message: Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_40710c060f1f134ba504552b7f2a3b3b

[2025-04-13T23:07:49.635+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T23:07:49.635+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 23:07:48.472372+00:00 end:2025-04-13 23:07:49.634468+00:00 duration:1.162096
[2025-04-13T23:07:49.636+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryInsertJobOperator): create_external_table_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-12 00:00:00+00:00: scheduled__2025-04-12T00:00:00+00:00, state:running, queued_at: 2025-04-13 23:07:36.629415+00:00. externally triggered: False>
[2025-04-13T23:07:49.636+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }; reason: invalid, message: Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }

Location: US
Job ID: ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_40710c060f1f134ba504552b7f2a3b3b
[2025-04-13T23:07:49.637+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=create_external_table_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T230748, end_date=20250413T230749
[2025-04-13T23:07:49.665+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:07:49.665+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task create_external_table_task (400 Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }; reason: invalid, message: Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_40710c060f1f134ba504552b7f2a3b3b
; 100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }; reason: invalid, message: Invalid source URI: { ti.xcom_pull(task_ids="local_to_gcs_task") }

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_40710c060f1f134ba504552b7f2a3b3b

[2025-04-13T23:07:49.693+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T23:07:49.725+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:07:49.726+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T23:30:56.173+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:30:56.187+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:30:56.192+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:30:56.193+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T23:30:56.199+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_table_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T23:30:56.203+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:30:56.204+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2025-04-13T23:30:56.204+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_external_table_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpxlvp84fy']
[2025-04-13T23:30:56.205+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask create_external_table_task
[2025-04-13T23:30:56.233+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 15a7108b06f8
[2025-04-13T23:30:56.278+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T23:30:56.279+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T23:30:56.279+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T23:30:56.279+0000] {logging_mixin.py:190} INFO - Current task name:create_external_table_task state:running start_date:2025-04-13 23:30:56.187446+00:00
[2025-04-13T23:30:56.279+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T23:30:56.279+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:30:56.280+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-13T23:30:56.280+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-13T23:30:56.281+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-13T23:30:56.308+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': "\n          CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{BIGQUERY_DATASET}.{EXTERNAL_TABLE}`\n          OPTIONS (\n            format = 'PARQUET',\n            uris = ['gs://nyc-projects-455321-bucket/raw/building_permits-2025-04-13-233054.parquet']\n          )\n        ", 'useLegacySql': False}}'
[2025-04-13T23:30:56.309+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3b28c30917738759477f1d07966baf08
[2025-04-13T23:30:56.727+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.; reason: invalid, location: {PROJECT_ID}.{BIGQUERY_DATASET}.{EXTERNAL_TABLE}, message: Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3b28c30917738759477f1d07966baf08

[2025-04-13T23:30:56.736+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T23:30:56.736+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 23:30:56.187446+00:00 end:2025-04-13 23:30:56.736108+00:00 duration:0.548662
[2025-04-13T23:30:56.737+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryInsertJobOperator): create_external_table_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-12 00:00:00+00:00: scheduled__2025-04-12T00:00:00+00:00, state:running, queued_at: 2025-04-13 23:30:43.197349+00:00. externally triggered: False>
[2025-04-13T23:30:56.737+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.; reason: invalid, location: {PROJECT_ID}.{BIGQUERY_DATASET}.{EXTERNAL_TABLE}, message: Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.

Location: US
Job ID: ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3b28c30917738759477f1d07966baf08
[2025-04-13T23:30:56.737+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=create_external_table_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T233056, end_date=20250413T233056
[2025-04-13T23:30:56.755+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:30:56.755+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task create_external_table_task (400 Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.; reason: invalid, location: {PROJECT_ID}.{BIGQUERY_DATASET}.{EXTERNAL_TABLE}, message: Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3b28c30917738759477f1d07966baf08
; 115)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.; reason: invalid, location: {PROJECT_ID}.{BIGQUERY_DATASET}.{EXTERNAL_TABLE}, message: Invalid project ID '{PROJECT_ID}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_3b28c30917738759477f1d07966baf08

[2025-04-13T23:30:56.797+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T23:30:56.815+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:30:56.816+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T23:37:43.566+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:37:43.577+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:37:43.582+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:37:43.583+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T23:37:43.589+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_table_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T23:37:43.593+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:37:43.594+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-04-13T23:37:43.596+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_external_table_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp5gywthma']
[2025-04-13T23:37:43.597+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask create_external_table_task
[2025-04-13T23:37:43.633+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 84d443f8c8f3
[2025-04-13T23:37:43.688+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T23:37:43.689+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T23:37:43.689+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T23:37:43.689+0000] {logging_mixin.py:190} INFO - Current task name:create_external_table_task state:running start_date:2025-04-13 23:37:43.577731+00:00
[2025-04-13T23:37:43.689+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T23:37:43.689+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:37:43.690+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-13T23:37:43.690+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-13T23:37:43.691+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-13T23:37:43.719+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          CREATE OR REPLACE EXTERNAL TABLE {PROJECT_ID}.{BIGQUERY_DATASET}.{EXTERNAL_TABLE}\n          OPTIONS (\n            format = \'PARQUET\',\n            uris = ["gs://nyc-projects-455321-bucket/raw/building_permits-2025-04-13-233741.parquet"]\n          )\n        ', 'useLegacySql': False}}'
[2025-04-13T23:37:43.720+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_7e8410a11d918c299e7847154ae24063
[2025-04-13T23:37:44.075+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected "{" at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected "{" at [2:44]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_7e8410a11d918c299e7847154ae24063

[2025-04-13T23:37:44.087+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T23:37:44.087+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 23:37:43.577731+00:00 end:2025-04-13 23:37:44.086417+00:00 duration:0.508686
[2025-04-13T23:37:44.088+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryInsertJobOperator): create_external_table_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-12 00:00:00+00:00: scheduled__2025-04-12T00:00:00+00:00, state:running, queued_at: 2025-04-13 23:37:32.434295+00:00. externally triggered: False>
[2025-04-13T23:37:44.088+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Syntax error: Unexpected "{" at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected "{" at [2:44]

Location: US
Job ID: ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_7e8410a11d918c299e7847154ae24063
[2025-04-13T23:37:44.088+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=create_external_table_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T233743, end_date=20250413T233744
[2025-04-13T23:37:44.111+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:37:44.112+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task create_external_table_task (400 Syntax error: Unexpected "{" at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected "{" at [2:44]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_7e8410a11d918c299e7847154ae24063
; 100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected "{" at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected "{" at [2:44]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_7e8410a11d918c299e7847154ae24063

[2025-04-13T23:37:44.143+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T23:37:44.185+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:37:44.187+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T23:40:46.395+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:40:46.407+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:40:46.412+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:40:46.413+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T23:40:46.419+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_table_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T23:40:46.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:40:46.425+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-04-13T23:40:46.427+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_external_table_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpbjavb3x8']
[2025-04-13T23:40:46.428+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask create_external_table_task
[2025-04-13T23:40:46.456+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 68e962a0d2c5
[2025-04-13T23:40:46.508+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T23:40:46.509+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T23:40:46.509+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T23:40:46.509+0000] {logging_mixin.py:190} INFO - Current task name:create_external_table_task state:running start_date:2025-04-13 23:40:46.407526+00:00
[2025-04-13T23:40:46.510+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T23:40:46.510+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:40:46.511+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-13T23:40:46.511+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-13T23:40:46.512+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-13T23:40:46.541+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          CREATE OR REPLACE EXTERNAL TABLE \'nyc-projects-455321.building_permits.external_table\'\n          OPTIONS (\n            format = \'PARQUET\',\n            uris = ["gs://nyc-projects-455321-bucket/raw/building_permits-2025-04-13-234044.parquet"]\n          )\n        ', 'useLegacySql': False}}'
[2025-04-13T23:40:46.542+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_dea6c049cbc208e5e664632180e57b04
[2025-04-13T23:40:46.904+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_dea6c049cbc208e5e664632180e57b04

[2025-04-13T23:40:46.922+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T23:40:46.922+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 23:40:46.407526+00:00 end:2025-04-13 23:40:46.921475+00:00 duration:0.513949
[2025-04-13T23:40:46.923+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryInsertJobOperator): create_external_table_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-12 00:00:00+00:00: scheduled__2025-04-12T00:00:00+00:00, state:running, queued_at: 2025-04-13 23:40:33.544092+00:00. externally triggered: False>
[2025-04-13T23:40:46.923+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]

Location: US
Job ID: ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_dea6c049cbc208e5e664632180e57b04
[2025-04-13T23:40:46.923+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=create_external_table_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T234046, end_date=20250413T234046
[2025-04-13T23:40:46.950+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:40:46.951+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task create_external_table_task (400 Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_dea6c049cbc208e5e664632180e57b04
; 100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]; reason: invalidQuery, location: query, message: Syntax error: Unexpected string literal 'nyc-projects-455321.building_permits.external_table' at [2:44]

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_dea6c049cbc208e5e664632180e57b04

[2025-04-13T23:40:46.978+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T23:40:47.015+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:40:47.018+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-13T23:43:10.018+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:43:10.030+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:43:10.035+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-13T23:43:10.036+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T23:43:10.042+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_table_task> on 2025-04-12 00:00:00+00:00
[2025-04-13T23:43:10.045+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:43:10.046+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-04-13T23:43:10.047+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_external_table_task', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpus9sul88']
[2025-04-13T23:43:10.048+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask create_external_table_task
[2025-04-13T23:43:10.072+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_external_table_task scheduled__2025-04-12T00:00:00+00:00 [running]> on host 0b262730a036
[2025-04-13T23:43:10.113+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-13T23:43:10.114+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T23:43:10.114+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T23:43:10.114+0000] {logging_mixin.py:190} INFO - Current task name:create_external_table_task state:running start_date:2025-04-13 23:43:10.030631+00:00
[2025-04-13T23:43:10.114+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T23:43:10.115+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:43:10.115+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-13T23:43:10.116+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-13T23:43:10.116+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-13T23:43:10.144+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': '\n          CREATE OR REPLACE EXTERNAL TABLE `nyc-projects-455321.building_permits.external_table`\n          OPTIONS (\n            format = \'PARQUET\',\n            uris = ["gs://nyc-projects-455321-bucket/raw/building_permits-2025-04-13-234308.parquet"]\n          )\n        ', 'useLegacySql': False}}'
[2025-04-13T23:43:10.145+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_f66adcddd2c9aca4e29620b155f2bcf1
[2025-04-13T23:43:11.327+0000] {bigquery.py:2636} INFO - Job ***_data_ingestion_gcs_dag_create_external_table_task_2025_04_12T00_00_00_00_00_f66adcddd2c9aca4e29620b155f2bcf1 is completed. Checking the job status
[2025-04-13T23:43:11.361+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:43:11.362+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=create_external_table_task, run_id=scheduled__2025-04-12T00:00:00+00:00, execution_date=20250412T000000, start_date=20250413T234310, end_date=20250413T234311
[2025-04-13T23:43:11.402+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-13T23:43:11.403+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-13T23:43:11.404+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-04-13 23:42:56.845209+00:00
[2025-04-13T23:43:11.404+0000] {logging_mixin.py:190} INFO - Task hostname:0b262730a036 operator:BigQueryInsertJobOperator
[2025-04-13T23:43:11.457+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T23:43:11.489+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:43:11.491+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
