[2025-04-14T01:39:46.390+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T01:39:46.401+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_temp_table_task manual__2025-04-14T01:29:06.354995+00:00 [queued]>
[2025-04-14T01:39:46.405+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_temp_table_task manual__2025-04-14T01:29:06.354995+00:00 [queued]>
[2025-04-14T01:39:46.406+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-14T01:39:46.413+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_temp_table_task> on 2025-04-14 01:29:06.354995+00:00
[2025-04-14T01:39:46.417+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=270) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T01:39:46.418+0000] {standard_task_runner.py:72} INFO - Started process 272 to run task
[2025-04-14T01:39:46.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_temp_table_task', 'manual__2025-04-14T01:29:06.354995+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpn4u0e7tx']
[2025-04-14T01:39:46.419+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask create_temp_table_task
[2025-04-14T01:39:46.446+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_temp_table_task manual__2025-04-14T01:29:06.354995+00:00 [running]> on host 04d41ae960dc
[2025-04-14T01:39:46.488+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_temp_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T01:29:06.354995+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T01:29:06.354995+00:00'
[2025-04-14T01:39:46.489+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T01:39:46.489+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T01:39:46.490+0000] {logging_mixin.py:190} INFO - Current task name:create_temp_table_task state:running start_date:2025-04-14 01:39:46.401648+00:00
[2025-04-14T01:39:46.490+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-14T01:39:46.490+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T01:39:46.491+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T01:39:46.491+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-14T01:39:46.492+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T01:39:46.520+0000] {bigquery.py:2665} INFO - Executing: {'query': {'query': "\n          CREATE OR REPLACE TABLE `nyc-projects-455321.building_permits.external_table`\n          AS\n          SELECT\n            borough,\n            job_type,\n            block,\n            lot,\n            PARSE_TIMESTAMP('%m-%d-%Y', issuance_date) AS issuance_date,\n            CAST(permit_si_no AS INT64) AS permit_si_no,\n            CAST(gis_latitude AS FLOAT64) AS gis_latitude,\n            CAST(gis_longitude AS FLOAT64) AS gis_longitude,\n            gis_nta_name\n          FROM `nyc-projects-455321.building_permits.external_table`;\n        ", 'useLegacySql': False}}'
[2025-04-14T01:39:46.521+0000] {bigquery.py:1241} INFO - Inserting job ***_data_ingestion_gcs_dag_create_temp_table_task_2025_04_14T01_29_06_354995_00_00_2b95f79e7e944dc84b557a403e3c83cf
[2025-04-14T01:39:47.530+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.; reason: invalid, message: nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_temp_table_task_2025_04_14T01_29_06_354995_00_00_2b95f79e7e944dc84b557a403e3c83cf

[2025-04-14T01:39:47.542+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T01:39:47.542+0000] {logging_mixin.py:190} INFO - Task start:2025-04-14 01:39:46.401648+00:00 end:2025-04-14 01:39:47.541889+00:00 duration:1.140241
[2025-04-14T01:39:47.542+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryInsertJobOperator): create_temp_table_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-14 01:29:06.354995+00:00: manual__2025-04-14T01:29:06.354995+00:00, state:running, queued_at: 2025-04-14 01:29:06.491456+00:00. externally triggered: True>
[2025-04-14T01:39:47.542+0000] {logging_mixin.py:190} INFO - Failure caused by 400 nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.; reason: invalid, message: nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.

Location: US
Job ID: ***_data_ingestion_gcs_dag_create_temp_table_task_2025_04_14T01_29_06_354995_00_00_2b95f79e7e944dc84b557a403e3c83cf
[2025-04-14T01:39:47.543+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=create_temp_table_task, run_id=manual__2025-04-14T01:29:06.354995+00:00, execution_date=20250414T012906, start_date=20250414T013946, end_date=20250414T013947
[2025-04-14T01:39:47.556+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T01:39:47.556+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task create_temp_table_task (400 nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.; reason: invalid, message: nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_temp_table_task_2025_04_14T01_29_06_354995_00_00_2b95f79e7e944dc84b557a403e3c83cf
; 272)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2731, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.; reason: invalid, message: nyc-projects-455321:building_permits.external_table is not allowed for this operation because it currently has type EXTERNAL.

Location: US
Job ID: airflow_data_ingestion_gcs_dag_create_temp_table_task_2025_04_14T01_29_06_354995_00_00_2b95f79e7e944dc84b557a403e3c83cf

[2025-04-14T01:39:47.583+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T01:39:47.593+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T01:39:47.594+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
