[2025-04-13T04:31:09.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T04:31:09.960+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-13T04:25:55.660106+00:00 [queued]>
[2025-04-13T04:31:09.964+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-13T04:25:55.660106+00:00 [queued]>
[2025-04-13T04:31:09.964+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-13T04:31:09.971+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_permits_task> on 2025-04-13 04:25:55.660106+00:00
[2025-04-13T04:31:09.975+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T04:31:09.976+0000] {standard_task_runner.py:72} INFO - Started process 167 to run task
[2025-04-13T04:31:09.977+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'fetch_permits_task', 'manual__2025-04-13T04:25:55.660106+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmphupaq3vf']
[2025-04-13T04:31:09.977+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask fetch_permits_task
[2025-04-13T04:31:10.003+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.fetch_permits_task manual__2025-04-13T04:25:55.660106+00:00 [running]> on host e117c5077d30
[2025-04-13T04:31:10.042+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='fetch_permits_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T04:25:55.660106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T04:25:55.660106+00:00'
[2025-04-13T04:31:10.043+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T04:31:10.043+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T04:31:10.044+0000] {logging_mixin.py:190} INFO - Current task name:fetch_permits_task state:running start_date:2025-04-13 04:31:09.960344+00:00
[2025-04-13T04:31:10.044+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-04-13T04:31:10.044+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T04:31:10.731+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 61, in fetch_permits
    results = client.get(DATASET_ID, offset=offset, limit=batch_size, where=f"issued_date > '{ti}'")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 412, in get
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 555, in _perform_request
    utils.raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/utils.py", line 30, in raise_for_status
    raise requests.exceptions.HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request.
	Query coordinator error: query.soql.type-mismatch; Type mismatch for op$>, is text; position: Map(row -> 1, column -> 727, line -> "SELECT `job_filing_number`, `filing_reason`, `house_no`, `street_name`, `borough`, `lot`, `bin`, `block`, `c_b_no`, `apt_condo_no_s`, `work_on_floor`, `work_type`, `permittee_s_license_type`, `applicant_license`, `applicant_first_name`, `applicant_middle_name`, `applicant_last_name`, `applicant_business_name`, `applicant_business_address`, `filing_representative_first_name`, `filing_representative_middle_initial`, `filing_representative_last_name`, `filing_representative_business_name`, `work_permit`, `approved_date`, `issued_date`, `expired_date`, `job_description`, `estimated_job_costs`, `owner_business_name`, `owner_name`, `owner_street_address`, `owner_city`, `owner_state`, `owner_zip_code` WHERE `issued_date` > \"None\" LIMIT 1000 OFFSET 0\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^")
[2025-04-13T04:31:10.761+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T04:31:10.762+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 04:31:09.960344+00:00 end:2025-04-13 04:31:10.760387+00:00 duration:0.800043
[2025-04-13T04:31:10.763+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_permits_task> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-04-13 04:25:55.660106+00:00: manual__2025-04-13T04:25:55.660106+00:00, state:running, queued_at: 2025-04-13 04:25:55.815037+00:00. externally triggered: True>
[2025-04-13T04:31:10.764+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Client Error: Bad Request.
	Query coordinator error: query.soql.type-mismatch; Type mismatch for op$>, is text; position: Map(row -> 1, column -> 727, line -> "SELECT `job_filing_number`, `filing_reason`, `house_no`, `street_name`, `borough`, `lot`, `bin`, `block`, `c_b_no`, `apt_condo_no_s`, `work_on_floor`, `work_type`, `permittee_s_license_type`, `applicant_license`, `applicant_first_name`, `applicant_middle_name`, `applicant_last_name`, `applicant_business_name`, `applicant_business_address`, `filing_representative_first_name`, `filing_representative_middle_initial`, `filing_representative_last_name`, `filing_representative_business_name`, `work_permit`, `approved_date`, `issued_date`, `expired_date`, `job_description`, `estimated_job_costs`, `owner_business_name`, `owner_name`, `owner_street_address`, `owner_city`, `owner_state`, `owner_zip_code` WHERE `issued_date` > \"None\" LIMIT 1000 OFFSET 0\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^")
[2025-04-13T04:31:10.765+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=fetch_permits_task, run_id=manual__2025-04-13T04:25:55.660106+00:00, execution_date=20250413T042555, start_date=20250413T043109, end_date=20250413T043110
[2025-04-13T04:31:10.807+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T04:31:10.807+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task fetch_permits_task (400 Client Error: Bad Request.
	Query coordinator error: query.soql.type-mismatch; Type mismatch for op$>, is text; position: Map(row -> 1, column -> 727, line -> "SELECT `job_filing_number`, `filing_reason`, `house_no`, `street_name`, `borough`, `lot`, `bin`, `block`, `c_b_no`, `apt_condo_no_s`, `work_on_floor`, `work_type`, `permittee_s_license_type`, `applicant_license`, `applicant_first_name`, `applicant_middle_name`, `applicant_last_name`, `applicant_business_name`, `applicant_business_address`, `filing_representative_first_name`, `filing_representative_middle_initial`, `filing_representative_last_name`, `filing_representative_business_name`, `work_permit`, `approved_date`, `issued_date`, `expired_date`, `job_description`, `estimated_job_costs`, `owner_business_name`, `owner_name`, `owner_street_address`, `owner_city`, `owner_state`, `owner_zip_code` WHERE `issued_date` > \"None\" LIMIT 1000 OFFSET 0\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^"); 167)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 61, in fetch_permits
    results = client.get(DATASET_ID, offset=offset, limit=batch_size, where=f"issued_date > '{ti}'")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 412, in get
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/socrata.py", line 555, in _perform_request
    utils.raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/sodapy/utils.py", line 30, in raise_for_status
    raise requests.exceptions.HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request.
	Query coordinator error: query.soql.type-mismatch; Type mismatch for op$>, is text; position: Map(row -> 1, column -> 727, line -> "SELECT `job_filing_number`, `filing_reason`, `house_no`, `street_name`, `borough`, `lot`, `bin`, `block`, `c_b_no`, `apt_condo_no_s`, `work_on_floor`, `work_type`, `permittee_s_license_type`, `applicant_license`, `applicant_first_name`, `applicant_middle_name`, `applicant_last_name`, `applicant_business_name`, `applicant_business_address`, `filing_representative_first_name`, `filing_representative_middle_initial`, `filing_representative_last_name`, `filing_representative_business_name`, `work_permit`, `approved_date`, `issued_date`, `expired_date`, `job_description`, `estimated_job_costs`, `owner_business_name`, `owner_name`, `owner_street_address`, `owner_city`, `owner_state`, `owner_zip_code` WHERE `issued_date` > \"None\" LIMIT 1000 OFFSET 0\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^")
[2025-04-13T04:31:10.856+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T04:31:10.886+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T04:31:10.887+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
